/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class nativedemo_NativeDemo */

#ifndef _Included_nativedemo_NativeDemo
#define _Included_nativedemo_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nativedemo_NativeDemo
 * Method:    gcd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_nativedemo_NativeDemo_gcd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
