/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class Native_NativeDemo */

#ifndef _Included_Native_NativeDemo
#define _Included_Native_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native_NativeDemo
 * Method:    gcd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Native_NativeDemo_gcd
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
